Deprecate useSparseFiles() and sparseCapacity. Fix #1063.
OpenHFT/Chronicle-Queue pull request #1067
Opened 2022-05-03 05:45 UTC by foroughgoudarzi

2022-05-03 07:06 UTC, minborg commented
Does this mean sparse files will always be used on platforms supporting sparse files?

2022-05-04 16:12 UTC, foroughgoudarzi commented
> 

I think so.

2022-05-05 07:18 UTC, rogersimmons approved these changes

2022-05-05 10:24 UTC, rogersimmons requested changes

2022-05-05 10:24 UTC, rogersimmons commented on src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java
> +        return OS.isSparseFileSupported()
This will always be true on Linux (change in behaviour)

2022-05-05 10:24 UTC, rogersimmons commented on src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueBuilder.java
> +        if (OS.isSparseFileSupported() &&
This will always be true on Linux

2022-05-05 10:24 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/ChunkCountTest.java
> +                final long expected = OS.isSparseFileSupported() ? 1 : 1 + (pos >> 18);
Change in behaviour

2022-05-05 10:24 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/QueueWriteDocumentContextTest.java
> +        useSparseFiles = OS.isSparseFileSupported();
Break

2022-05-05 10:24 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/WriteBytesTest.java
> +            final boolean useSparseFiles = OS.isSparseFileSupported();
Break

2022-05-05 10:35 UTC, rogersimmons commented
The change as currently made alters the behaviour (dramatically).
The previous useSpareFiles build option defaulted false and was only set true in very rare cases. This change replaced that with OS.isSpareFileSupported which will always be true on Linux - so we end up always using sparse files, rather than only rarely.

The change here is:
1. deprecate the old useSparseFiles variable and any interface which uses them (you have done this)
2. The various bits of code which sample useSparseFiles should be left as they currently are (ie they will activate only if useSparseFiles is true)
3. When we eventually remove useSparseFiles (2 versions after deprecating) any code which follows the useSparseFiles=true path should be removed
4. The related changes to support capped blockSizes is already done

2022-05-05 13:41 UTC, minborg commented
> The change as currently made alters the behaviour (dramatically). The previous useSpareFiles build option defaulted false and was only set true in very rare cases. This change replaced that with OS.isSpareFileSupported which will always be true on Linux - so we end up always using sparse files, rather than only rarely.

This is precisely what I said so either we are both wrong and the entire thing is unclear or we are right and there is a fundamental behavioral change introduced. In either case, it is a bad thing.

2022-05-05 16:02 UTC, rogersimmons commented
Hi @minborg - there is no fundamental issue here. This change is to deprecate (and eventually remove) the need for users to explicitly call options to instigate the use of sparse files. Instead, the user should use the standard queue interface as usual (normal blockSize etc), then if they use the queue in a sparse manner everything just works transparently. The OS will handle the sparseness under the covers.

This is different to just switching the old sparseFiles flag to default true (from false) as this alters the memory-mapping philosophy to always use one large file rather than blocksizes, which in turn puts excessive virtual memory load on the process.

See the below example which maps a queue normally, but uses it in a sparse manner. Nothing needs to be set for this to work - it just works out of the box transparently. Although the cq4 file appears huge, only 16kB is used.

```
public void sparse() {
        try( ChronicleQueue queue = SingleChronicleQueueBuilder.binary("/dev/shm/large")
                .blockSize(64 << 20)
                .build()) {

            ExcerptAppender appender = queue.acquireAppender();

            try(DocumentContext dc = appender.writingDocument()) {
                dc.wire().bytes().writeInt(64L << 30, 123);
            }
        }
    }
```

```
rw-r--r-- 1 user users 68803362816 May  5 16:51 20220505F.cq4
rw-r--r-- 1 user users      131072 May  5 16:51 metadata.cq4t
```

```
$> hexdump -C 20220505F.cq4 
00000000  c0 00 00 40 b9 06 68 65  61 64 65 72 b6 08 53 43  |...@..header..SC|
00000010  51 53 74 6f 72 65 82 a9  00 00 00 cd 77 72 69 74  |QStore......writ|
00000020  65 50 6f 73 69 74 69 6f  6e 8e 01 00 00 00 00 8d  |ePosition.......|
00000030  02 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00  |................|
00000040  08 01 01 00 00 00 00 00  00 00 00 00 08 01 01 00  |................|
00000050  c8 69 6e 64 65 78 69 6e  67 b6 0c 53 43 51 53 49  |.indexing..SCQSI|
00000060  6e 64 65 78 69 6e 67 82  4c 00 00 00 ca 69 6e 64  |ndexing.L....ind|
00000070  65 78 43 6f 75 6e 74 a5  00 10 cc 69 6e 64 65 78  |exCount....index|
00000080  53 70 61 63 69 6e 67 a5  00 01 cb 69 6e 64 65 78  |Spacing....index|
00000090  32 49 6e 64 65 78 8f a7  c4 00 00 00 00 00 00 00  |2Index..........|
000000a0  c9 6c 61 73 74 49 6e 64  65 78 8e 00 00 00 00 a7  |.lastIndex......|
000000b0  00 01 00 00 00 00 00 00  ca 64 61 74 61 46 6f 72  |.........dataFor|
000000c0  6d 61 74 01 20 80 00 40  b9 0b 69 6e 64 65 78 32  |mat. ..@..index2|
000000d0  69 6e 64 65 78 8f 8f 8d  00 10 00 00 00 00 00 00  |index...........|
000000e0  01 00 00 00 00 00 00 00  e8 80 00 00 00 00 00 00  |................|
000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000080e0  00 00 00 00 00 00 00 00  1c 80 00 40 b9 05 69 6e  |...........@..in|
000080f0  64 65 78 8f 8f 8f 8f 8d  00 10 00 00 00 00 00 00  |dex.............|
00008100  01 00 00 00 00 00 00 00  08 01 01 00 00 00 00 00  |................|
00008110  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00010100  00 00 00 00 00 00 00 00  01 00 00 00 8f 00 00 00  |................|
00010110  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
1000000000  7b 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |{...............|
1000000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
1005000000
```

```
$> du -h 20220505F.cq4 
16K     20220505F.cq4
```

2022-06-06 19:43 UTC, foroughgoudarzi commented
@peter-k-lawrey and @rogersimmons I pushed new changes. This time all the tests passed and the build was successful. @peter-lawrey  I hope I understood what you said today correctly: (Sparse files are used) if and only if (OS allows and blockSize has not been set) based on this I updated the tests too. 
Please take a look.

2022-06-07 14:01 UTC, rogersimmons requested changes
Hi @Forough - you're trying to do too much at this stage. See my earlier comment on May 5th.
All you need to do here is:
1. mark as deprecated the old useSparseFiles variables/interface
2. Leave the (now deprecated) sparse file functionality as is. Nothing to change here.
3. Eventually (not now - 2 versions time) we can then remove the code which depends on useSparseFiles
4. Add a cap on blockSizes (already done)

So from here, you just need to revert most of the changes - as highlighted.
The rest of the changes are for a later date.

2022-06-07 14:01 UTC, rogersimmons commented on src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java
> +        return blockSize == 0
revert (to return useSparseFiles)

2022-06-07 14:01 UTC, rogersimmons commented on src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueBuilder.java
> +       // long bs = blockSize == null ? OS.is64Bit() ? 64L << 20 : QueueUtil.testBlockSize() : blockSize;
revert (uncomment)

2022-06-07 14:01 UTC, rogersimmons commented on src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueBuilder.java
> +        return blockSize != null ? Math.max(minSize, blockSize) : 0;
revert (return Math.max(minSize, bs); )

2022-06-07 14:01 UTC, rogersimmons commented on src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueBuilder.java
> +        return Math.max(minSize, DEFAULT_SPARSE_CAPACITY);
revert (lines 690, 691, and 694. remove 695)

2022-06-07 14:01 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/ChunkCountTest.java
> +                final long expected = OS.isSparseFileSupported() && builder.blockSize() == 0 ? 1 : 1 + (pos >> 18);
revert (to final... builder.useSparseFiles()...)

2022-06-07 14:01 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/QueueWriteDocumentContextTest.java
> +        useSparseFiles = OS.isSparseFileSupported() && builder.blockSize() == 0;
revert (to use... = builder.useSparseFiles(); )

2022-06-07 14:01 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/WriteBytesTest.java
> +                .blockSize(OS.isWindows() ? 64 << 10 : OS.pageSize())
revert (remove)

2022-06-07 14:01 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/WriteBytesTest.java
> +            final boolean useSparseFiles = OS.isSparseFileSupported() && builder.blockSize() == 0;
revert (to builder.useSparseFiles())

2022-06-07 14:01 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/cleanup/OnReleaseTest.java
> +                .blockSize(OS.isWindows() ? 64 << 10 : OS.pageSize())
revert (remove)

2022-06-07 14:01 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/cleanup/OnReleaseTest.java
> +                     .blockSize(OS.isWindows() ? 64 << 10 : OS.pageSize())
revert (remove)

2022-06-07 14:01 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/impl/single/MicroToucherTest.java
> +        touchPage(b -> b.rollCycle(RollCycles.HUGE_DAILY), 66561);
revert (to b.useSparseFiles(true)...)

2022-06-07 14:01 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/impl/single/SparseBinarySearchTest.java
> +                .blockSize(OS.isWindows() ? 64 << 10 : OS.pageSize())
revert

2022-06-07 14:01 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/impl/single/StoreAppenderInternalWriteBytesTest.java
> +                .blockSize(OS.isWindows() ? 64 << 10 : OS.pageSize())
revert

2022-06-07 14:01 UTC, rogersimmons commented on src/test/java/net/openhft/chronicle/queue/impl/single/TestBinarySearch.java
> +                .blockSize(OS.isWindows() ? 64 << 10 : OS.pageSize())
revert

2022-06-07 15:45 UTC, rogersimmons approved these changes

2022-06-07 15:46 UTC, merged