Backport pretoucher fixes to .23
OpenHFT/Chronicle-Queue pull request #1210
Opened 2022-10-06 05:03 UTC by nicktindall

If this looks good I'll use it to go back to .22 (it incorporates changes made to Queue and Queue Enterprise on develop)

2022-10-06 05:13 UTC, JerryShea commented on src/main/java/net/openhft/chronicle/queue/impl/single/Pretoucher.java
> -    public void shutdown() {
need to bring this function back - can't change API in stable release

2022-10-06 06:13 UTC, nicktindall commented on src/test/java/net/openhft/chronicle/queue/IndexForIDTest.java
> +        ignoreException("This functionality has been deprecated and in future will only be available in Chronicle Queue Enterprise");
For some reason this didn't occur in the Mac build so I had to ignore instead of expect

2022-10-06 09:18 UTC, alamar requested changes
We need pretoucher stress test (without ea) to make sure this works.

2022-10-06 09:18 UTC, alamar commented on src/main/java/net/openhft/chronicle/queue/impl/single/Pretoucher.java
> -    private boolean checkEA(boolean ea) {
I suggest keeping ea an x.24-only feature

2022-10-06 09:18 UTC, alamar commented on src/main/java/net/openhft/chronicle/queue/impl/single/PretoucherState.java
> +                            if (bytes != null && capacity > 0) {
I'm not sure what this does

2022-10-06 09:18 UTC, alamar commented on src/main/java/net/openhft/chronicle/queue/impl/single/QueueFileShrinkManager.java
> +    }
This change seems unrelated to the job.

2022-10-06 10:10 UTC, nicktindall commented on src/main/java/net/openhft/chronicle/queue/impl/single/PretoucherState.java
> +                            if (bytes != null && capacity > 0) {
@JerryShea's changes

2022-10-06 10:10 UTC, nicktindall commented on src/main/java/net/openhft/chronicle/queue/impl/single/QueueFileShrinkManager.java
> +    }
@JerryShea again

2022-10-06 10:57 UTC, alamar commented on src/main/java/net/openhft/chronicle/queue/impl/single/PretoucherState.java
> +                            if (bytes != null && capacity > 0) {
Can we merge that as a separate PR/commit perhaps?

2022-10-06 19:02 UTC, nicktindall commented on src/main/java/net/openhft/chronicle/queue/impl/single/PretoucherState.java
> +                            if (bytes != null && capacity > 0) {
They are separate commits. Happy to break them out to a separate PR if it'll make things clearer.

2022-10-06 20:39 UTC, alamar commented on src/main/java/net/openhft/chronicle/queue/impl/single/PretoucherState.java
> +                            if (bytes != null && capacity > 0) {
I suggest doing that, even as there are conflicts already.

2022-10-06 20:57 UTC, nicktindall commented on src/main/java/net/openhft/chronicle/queue/impl/single/PretoucherState.java
> +                            if (bytes != null && capacity > 0) {
@JerryShea changes expunged, conflicts resolved. Sorry @JerryShea.

2022-10-06 21:19 UTC, alamar commented on src/main/java/net/openhft/chronicle/queue/impl/single/Pretoucher.java
> -    private boolean checkEA(boolean ea) {
I still suggest bringing this check back!

2022-10-06 22:29 UTC, nicktindall commented on src/main/java/net/openhft/chronicle/queue/impl/single/Pretoucher.java
> -    private boolean checkEA(boolean ea) {
Given that x.24 and x.23 are basically the same code, should we not be able to apply the fixes from x.24 and resurrect `earlyAcquireNextCycle` for x.23, I believe I back-ported all the tests and they seem to be working. @JerryShea what are your thoughts on this?

2022-10-07 00:33 UTC, JerryShea commented on src/main/java/net/openhft/chronicle/queue/impl/single/Pretoucher.java
> -    private boolean checkEA(boolean ea) {
Yes please leave checkEA in this version

2022-10-07 04:04 UTC, nicktindall commented on src/test/java/net/openhft/chronicle/queue/impl/single/PretoucherTest.java
>              assertEquals(11, capturedCycles.size());
This got changed to 12 in develop, but I had to take it back to 11, I assume it's something to do with EA

2022-10-07 04:04 UTC, nicktindall commented on src/main/java/net/openhft/chronicle/queue/impl/single/Pretoucher.java
> -    private boolean checkEA(boolean ea) {
OK done

2022-10-07 05:48 UTC, JerryShea approved these changes

2022-10-07 07:32 UTC, alamar approved these changes

2022-10-07 07:49 UTC, merged