Store the index we've normalisedEOFs to...
OpenHFT/Chronicle-Queue pull request #1311
Opened 2023-02-28 01:09 UTC by nicktindall

... to avoid re-normalising the queue from the beginning each time. Fixes #1306

2023-02-28 01:12 UTC, nicktindall commented on src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java
> +                    return longValue;
I don't know why this was returning null?

2023-02-28 01:42 UTC, JerryShea approved these changes
nice

2023-02-28 02:39 UTC, nicktindall commented on src/test/java/net/openhft/chronicle/queue/impl/single/NormaliseEOFsTest.java
> +        ignoreException(ex -> true, "Ignore everything");
This is a bit naughty. We probably should add a way to ask for debug exceptions and iterate over the exceptions in order.

2023-02-28 09:09 UTC, rogersimmons reviewed
Is this feature needed?
Isn't it enough to walk backwards from the most recent, writing EOFs where missing, then stopping at the first file with an EOF already present?

2023-02-28 09:36 UTC, nicktindall commented
> Is this feature needed?
> Isn't it enough to walk backwards from the most recent, writing EOFs where missing, then stopping at the first file with an EOF already present?
> 

Apparently not. We did prototype that but @alamar [made the point](https://github.com/OpenHFT/Chronicle-Queue/issues/1306#issuecomment-1439896535) that there can be numerous pre-touched cycles present when earlyAcquireNextCycle is turned on.

I would much prefer to do this without adding state, but until we've made the early acquired cycles distinguishable from actual cycles I fear that's not a possibility. This should be considered a stop gap until we can do that or similar.

2023-02-28 09:56 UTC, rogersimmons commented
ok, but isn't this the problem which needs to be fixed then (rather than adding more state to tolerate it)?
"there can be numerous pre-touched (EOF-less) cycles present when earlyAcquireNextCycle is turned on"

2023-02-28 09:57 UTC, nicktindall commented
> ok, but isn't this the problem which needs to be fixed then (rather than adding more state to tolerate it)?
> "there can be numerous pre-touched (EOF-less) cycles present when earlyAcquireNextCycle is turned on" 

Yes, agreed

2023-02-28 10:07 UTC, rogersimmons requested changes
Could you add an issue (tagged as high priority) to address the root cause and link it back to this ticket pls.
Also wrap all changes on this ticket with an explicit comment so they can easily be removed in due course. (The hash/annotate alone won't be enough as may not survive long).

Will then approve 
Thanks

2023-03-02 04:25 UTC, nicktindall commented
> Could you add an issue (tagged as high priority) to address the root cause and link it back to this ticket pls. Also wrap all changes on this ticket with an explicit comment so they can easily be removed in due course. (The hash/annotate alone won't be enough as may not survive long).
> 
> Will then approve Thanks

I created https://github.com/ChronicleEnterprise/Chronicle-Queue-Enterprise/issues/423 which should remove the need for normaliseEOFs altogether. This code will all be deleted naturally then because it's primarily to do with normaliseEOFs.

2023-03-02 08:07 UTC, rogersimmons approved these changes
Thanks Nick. Have approved

2023-03-02 09:44 UTC, merged