LastAcknowledgedIndexReplicatedStrategy WIP
OpenHFT/Chronicle-Queue pull request #1413
Opened 2023-08-08 08:10 UTC by JerryShea

WIP don't merge

2025-01-07 23:29 UTC, benbonavia commented on src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java
> +            long newValue = lastAcknowledgedIndexReplicatedStrategy.onAckReceived(acknowledgeIndex, remoteHostId);
this lastAcknowledgedIndexReplicationStrategy needs its own null checking -> should it be within this if block of along side it?

2025-01-08 03:53 UTC, tgd requested changes

2025-01-08 03:53 UTC, tgd commented on src/main/java/net/openhft/chronicle/queue/impl/single/LastAcknowledgedIndexReplicatedStrategy.java
> +public interface LastAcknowledgedIndexReplicatedStrategy {
Please add javadoc

2025-01-08 03:57 UTC, tgd commented on src/main/java/net/openhft/chronicle/queue/impl/single/LastAcknowledgedIndexReplicatedStrategy.java
> +public interface LastAcknowledgedIndexReplicatedStrategy {
What is the acceptable range of values that `onAckReceived` can return?

2025-01-13 05:09 UTC, JerryShea commented
Approved by me

2025-01-20 21:15 UTC, tgd approved these changes

2025-01-22 04:21 UTC, benbonavia approved these changes

2025-01-22 04:21 UTC, merged