Improve linearSCan warning and make it off by default #1555
OpenHFT/Chronicle-Queue pull request #1556
Opened 2024-04-05 14:03 UTC by peter-lawrey

2024-04-07 21:42 UTC, JerryShea commented on src/main/java/net/openhft/chronicle/queue/impl/single/SCQIndexing.java
> +    private void doPrintLinerScanTime(long toIndex, long fromKnownIndex, long start, String desc, long end) {
Liner should be Linear

2024-04-08 08:53 UTC, tgd requested changes
Thanks Peter - just two minor spelling fixes needed

2024-04-08 08:53 UTC, tgd commented on src/main/java/net/openhft/chronicle/queue/impl/single/SCQIndexing.java
> +    private long lastScanedIndex = -1;
`lastScanedIndex` -> `lastScannedIndex`

2024-04-09 02:18 UTC, nicktindall commented on src/main/java/net/openhft/chronicle/queue/impl/single/SCQIndexing.java
> +        if (end < start + 100_000)
Should `100_000` be a constant?

perhaps

```java
private static final int LINEAR_SCAN_WARN_THRESHOLD_NS = TimeUnit.MICROSECONDS.toNanos(100);
```

2024-04-12 08:47 UTC, tgd approved these changes

2024-04-15 14:30 UTC, merged