Feature/only unlock if process dead
OpenHFT/Chronicle-Queue pull request #987
Opened 2021-12-31 05:03 UTC by JerryShea

2022-01-02 16:55 UTC, RobAustin requested changes
we discussed this in the dev meeting, and the consensus was that we should consider other approaches than throwing an UnrecoverableTimeoutException() and forcing the user to run some other code ( such as Unlock Main ) to remove the lock.

2022-01-03 23:03 UTC, JerryShea commented
Let's discuss at dev meeting again this week. Only behaviour change introduced in this PR is if the new `queue.lock.recover.dead.process` parameter is set, and then we behave consistently with the append lock i.e. we unlock if the locking process is dead, otherwise throw exception

2022-01-19 10:13 UTC, RobAustin approved these changes

2022-01-20 02:53 UTC, nicktindall commented on src/main/java/net/openhft/chronicle/queue/impl/single/TableStoreWriteLock.java
> +                forceUnlock(value);
I feel like the value variable could be named better (e.g. currentLockValue or currentPID or whatever it is

2022-01-20 02:53 UTC, nicktindall commented on src/main/java/net/openhft/chronicle/queue/impl/single/TableStoreWriteLock.java
> +                forceUnlock(value);
Now we're increasing the number of lines between where it's assigned and where it's used

2022-01-20 02:54 UTC, nicktindall approved these changes
I like this change. Perhaps it should become default in .23?

2022-01-21 02:20 UTC, JerryShea commented
> I like this change. Perhaps it should become default in .23?
> 
> Although if we do that maybe we should have config like `forceUnlockOnTimeoutWhen` = `[ALWAYS | NEVER | LOCKING_PROCESS_DEAD]` rather than having `queue.lock.recover.dead.process` and `queue.dont.recover.lock.timeout` as separate and possibly inconsistent confgs

We normally give users two releases before we change things like this, but happy to take votes from the group.

I have implemented the enum which was very helpful - it helped shake out some inconsistencies (and further reinforces the case to refactor these locking classes)

2022-01-21 03:04 UTC, JerryShea commented on src/main/java/net/openhft/chronicle/queue/impl/single/TSQueueLock.java
> +        warnLock(msg, value);
duplicated but not quite the same code - we should address with https://github.com/OpenHFT/Chronicle-Queue/issues/994

2022-01-21 03:05 UTC, JerryShea commented on src/test/java/net/openhft/chronicle/queue/impl/single/TSQueueLockTest.java
> +public class TSQueueLockTest extends QueueTestCommon {
this is copy/pasted from TableStoreWriteLockTest. This test definitely needs some more work/refactoring - see https://github.com/OpenHFT/Chronicle-Queue/issues/994

2022-01-25 00:53 UTC, merged